python ./main.py \
  --exp_name cost2100/seed42/test\
  --train_path /storage/hujiacong/zxd/datasets/cost2100/in_test.pt \
  --val_path /storage/hujiacong/zxd/datasets/cost2100/in_val.pt \
  --test_path /storage/hujiacong/zxd/datasets/cost2100/in_test.pt \
  --epochs 400 \
  --d_model 64 \
  --nt 32 \
  --nc 32 \
  --dim_feedforward 2048 \
  --batch_size 32 \
  --workers 4 \
  --cr 4 \
  --scheduler cosine \
  --lr_init 2e-4 \
  --weight_decay 1e-3 \
  --gpu 0 \
  --seed 42 \
  --pretrained /storage/hujiacong/zxd/Huawei/TransNet/exps/COST2100/seed42/base/checkpoints/best_nmse.pth \
  --evaluate \