python ./main.py \
  --exp_name exp1 \
  --train_path /home/z-jiuri/workspace/Huawei/TransNet/data/COST2100/in_train.pt \
  --val_path /home/z-jiuri/workspace/Huawei/TransNet/data/COST2100/in_val.pt \
  --test_path /home/z-jiuri/workspace/Huawei/TransNet/data/COST2100/in_test.pt \
  --epochs 400 \
  --d_model 64 \
  --nt 32 \
  --nc 32 \
  --dim_feedforward 2048 \
  --batch_size 200 \
  --workers 4 \
  --cr 4 \
  --scheduler cosine \
  --lr_init 5e-4 \
  --gpu 0